git:
  paging:
    colorArg: never
    pager: ydiff -p cat -s --wrap --width={{columnWidth}}
    # externalDiffCommand: difft --display=side-by-side-show-both --syntax-highlight=off

# quitOnTopLevelReturn: false
gui:
  sidePanelWidth: 0.25

